apiVersion: skaffold/v1
kind: Config
metadata:
  name: monitoring-agent
deploy:
  kubectl:
    manifests:
    - k8s/monitoring-agent.yml
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
  - image: harbor.cyverse.org/de/monitoring-agent
