apiVersion: apps/v1
kind: Daemonset
metadata:
  name: monitoring-agent
spec:
  selector:
    matchLabels:
      de-app: monitoring-agent
  template:
    metadata:
      labels:
        de-app: monitoring-agent
        app: de
    spec:
      serviceAccount: configurator
      restartPolicy: Always
      volumes:
        - name: localtime
          hostPath:
            path: /etc/localtime
        - name: timezone
          configMap:
            name: timezone
            items:
              - key: timezone
                path: timezone
        - name: service-configs
          secret:
            secretName: service-configs
            items:
              - key: jobservices.yml
                path: service.yml
        - name: nats-client-tls
          secret:
            secretName: nats-client-tls
        - name: nats-services-creds
          secret:
            secretName: nats-services-creds
        - name: nats-configuration
          emptyDir: {}
      initContainers:
      - name: nats-configurator
        image: harbor.cyverse.org/de/nats-configurator
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
                fieldPath: metadata.namespace
        volumeMounts:
          - name: nats-configuration
            mountPath: /etc/cyverse/de/env
      containers:
      - name: monitoring-agent
        image: harbor.cyverse.org/de/monitoring-agent
        env:

        resources:
          requests:
            cpu: "1m"
            memory: "128Mi"
          limits:
            cpu: "100m"
            memory: "256Mi"
        args:
          - --log-level
          - debug
        env:
          - name: DISCOENV_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace

          - name: DISCOENV_NODE
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName

          - name: DISCOENV_DNS_INTERNAL_HOSTNAMES
            value: kubernetes.default.svc

          - name: DISCOENV_DNS_EXTERNAL_HOSTNAMES
            value: "cyverse.org,google.com"

          - name: DISCOENV_DNS_CHECKINTERVAL
            value: "2m"

          - name: DISCOENV_HEARTBEAT_INTERVAL
            value: "10s"

          - name: DISCOENV_NATS_TLS_CERT
            valueFrom:
              secretKeyRef:
                name: configs
                key: NATS_TLS_CERT

          - name: DISCOENV_NATS_TLS_KEY
            valueFrom:
              secretKeyRef:
                name: configs
                key: NATS_TLS_KEY

          - name: DISCOENV_NATS_TLS_CA_CERT
            valueFrom:
              secretKeyRef:
                name: configs
                key: NATS_TLS_CA_CERT

          - name: DISCOENV_NATS_CREDS_PATH:
            valueFrom:
              secretKeyRef:
                name: configs
                key: NATS_CREDS_PATH

          - name: DISCOENV_NATS_RECONNECTS_MAX
            valueFrom:
              secretKeyRef:
                name: configs
                key: NATS_RECONNECTS_MAX

          - name: DISCOENV_NATS_RECONNECTS_WAIT
            valueFrom:
              secretKeyRef:
                name: configs
                key: NATS_RECONNECTS_WAIT

          - name: DISCOENV_NATS_BASESUBJECT
            value: cyverse.monitoring.agent

          - name: DISCOENV_NATS_BASEQUEUE
            value: cyverse.monitoring.agent

          - name: OTEL_TRACES_EXPORTER
            valueFrom:
              secretKeyRef:
                name: configs
                key: OTEL_TRACES_EXPORTER
                
          - name: OTEL_EXPORTER_JAEGER_ENDPOINT
            valueFrom:
              secretKeyRef:
                name: configs
                key: OTEL_EXPORTER_JAEGER_HTTP_ENDPOINT
        volumeMounts:
          - name: localtime
            mountPath: /etc/localtime
            readOnly: true
          - name: timezone
            mountPath: /etc/timezone
            subPath: timezone
          - name: service-configs
            mountPath: /etc/cyverse/de/configs
            readOnly: true
          - name: nats-client-tls
            mountPath: /etc/nats/tls
            readOnly: true
          - name: nats-services-creds
            mountPath: /etc/nats/creds
            readOnly: true
          - name: nats-configuration
            mountPath: /etc/cyverse/de/env
            readOnly: true
        livenessProbe:
          httpGet:
            path: /debug/vars
            port: 60000
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /debug/vars
            port: 60000
          initialDelaySeconds: 5
          periodSeconds: 5
